"""Create sample, runsheet and step_process tables

Revision ID: 60db473cebd2
Revises: 897420cfecb1
Create Date: 2025-12-21 18:15:30.705841

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60db473cebd2'
down_revision = '897420cfecb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runsheet',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citic_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('material', sa.Enum('graphene', 'mos2', 'ws2', 'silicon', 'other', name='material'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('state', sa.Enum('edit', 'review', 'accepted', 'running', 'finished', name='runsheetstate'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runsheet_citic_id'), 'runsheet', ['citic_id'], unique=True)
    op.create_table('sample',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citic_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('exist', sa.Boolean(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('type', sa.Enum('wafer', 'dice', 'other', name='sampletype'), nullable=False),
    sa.Column('material', sa.Enum('graphene', 'mos2', 'ws2', 'silicon', 'other', name='material'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_citic_id'), 'sample', ['citic_id'], unique=True)
    op.create_table('step_process',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('system', sa.Enum('wet_bench', 'ald_oxford', 'ald_picosun', 'other', name='stepsystem'), nullable=False),
    sa.Column('machine_time', sa.Float(), nullable=False),
    sa.Column('engineer_time', sa.Float(), nullable=False),
    sa.Column('date_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_process')
    op.drop_index(op.f('ix_sample_citic_id'), table_name='sample')
    op.drop_table('sample')
    op.drop_index(op.f('ix_runsheet_citic_id'), table_name='runsheet')
    op.drop_table('runsheet')
    # ### end Alembic commands ###
