"""Add relationships to user, sample, runsheet and stepProcess

Revision ID: 6d8f76d5e3cd
Revises: 60db473cebd2
Create Date: 2025-12-21 18:34:57.503129

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d8f76d5e3cd'
down_revision = '60db473cebd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_runsheet_sample',
    sa.Column('runsheet_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['runsheet_id'], ['runsheet.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'runsheet_id')
    )
    op.create_table('link_sample_supervisor',
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'user_id')
    )
    op.create_table('link_sample_step_process',
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('step_process_id', sa.Uuid(), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.ForeignKeyConstraint(['step_process_id'], ['step_process.id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'step_process_id')
    )
    op.add_column('runsheet', sa.Column('reviewer_id', sa.Uuid(), nullable=True))
    op.add_column('runsheet', sa.Column('creator_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'runsheet', 'user', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'runsheet', 'user', ['creator_id'], ['id'], ondelete='CASCADE')
    op.add_column('sample', sa.Column('parent_sample_id', sa.Uuid(), nullable=True))
    op.add_column('sample', sa.Column('creator_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'sample', 'user', ['creator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sample', 'sample', ['parent_sample_id'], ['id'])
    op.add_column('step_process', sa.Column('engineer_id', sa.Uuid(), nullable=True))
    op.add_column('step_process', sa.Column('runsheet_id', sa.Uuid(), nullable=False))
    op.add_column('step_process', sa.Column('creator_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'step_process', 'user', ['creator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'step_process', 'runsheet', ['runsheet_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'step_process', 'user', ['engineer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step_process', type_='foreignkey')
    op.drop_constraint(None, 'step_process', type_='foreignkey')
    op.drop_constraint(None, 'step_process', type_='foreignkey')
    op.drop_column('step_process', 'creator_id')
    op.drop_column('step_process', 'runsheet_id')
    op.drop_column('step_process', 'engineer_id')
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'creator_id')
    op.drop_column('sample', 'parent_sample_id')
    op.drop_constraint(None, 'runsheet', type_='foreignkey')
    op.drop_constraint(None, 'runsheet', type_='foreignkey')
    op.drop_column('runsheet', 'creator_id')
    op.drop_column('runsheet', 'reviewer_id')
    op.drop_table('link_sample_step_process')
    op.drop_table('link_sample_supervisor')
    op.drop_table('link_runsheet_sample')
    # ### end Alembic commands ###
